### ISSUE TITLE
Capturing Seven LDR Exposures with Canon 5D MKIII

### ISSUE THREAD

**Issue by gerwang** [YilingQiao/DMRF#3]
Hi @YilingQiao, first off, thanks for your incredible work!

I want to capture my own data following your paper's description in Appendix E.1. I'm looking to capture a bracketed series of seven LDR exposures with my Canon EOS 5D MKIII. However, it seems the camera only supports three exposures at once.

Do I need the Canon SDK for seven exposures, and can you recommend GitHub projects that work with the Canon SDK to achieve this?

Thanks!

**Comment by YilingQiao** [comment]
Hi, gerwang, thanks for your interest. Hi, @gaoalexander , do you have any idea about the Canon SDK?

**Comment by gaoalexander** [comment]
Hi @gerwang, I believe that you should be able to shoot a bracketed exposure of 7 images directly in the camera without using the Canon SDK.  Try to go to the Custom Functions `C:Fn2` menu tab (different from the `SHOOT2` tab where you choose the exposure interval).  There should be an option called `Number of Bracketed Shots`, which will let you choose between 2, 3, 5, or 7 shots.  Once you have changed this property, then when you go back to the SHOOT2 tab, you should see that you are now setting the exposure range over 7 images.  I hope this helps!  Let us know if you are still unable to get this working, and we can troubleshoot further.
