### ISSUE TITLE
Trouble estimating lighting in a scene

### ISSUE THREAD

**Issue by CodenameWaddles** [YilingQiao/DMRF#5]
Hello, I'm trying to estimate the lighting on my own data, I managed to run the geometry estimation but I don't seem to have the files that `lighting_estimation/optimize.py` needs (`uv_weights.npy` for example).
Could you provide the structure of data that `lighting_estimation/optimize.py` needs to function correctly ?
Thanks

**Comment by YilingQiao** [comment]
Hi, Alexander, would you mind taking a look at this issue? @gaoalexander

**Comment by gaoalexander** [comment]
Hi @CodenameWaddles , I believe that `uv_weights.npy` was mainly an experimental feature, related to weighting the contribution to the error proportional to how often a given coordinate in UV space was observed.  There is also an additional segmentation loss that should be turned off by default. 

Also, please see the README for more information about how to preprocess your own data, as well as downloading the example datasets we have provided: https://github.com/YilingQiao/DMRF/blob/cleaning/preprocess/README.md

Finally, configuration files for individual scenes (our conference and lamp demo scenes) can be found here: https://github.com/YilingQiao/DMRF/tree/cleaning/preprocess/lighting_estimation/scenes

Closing this issue.  Please feel free to re-open it if you are still having issues.
